### ISSUE TITLE
Dfsu: spatial selection of 3D file yields inconsistent amount of elements compared to layer based selection

### ISSUE THREAD

**Issue by ovho-dhi** [DHI/mikeio#377]
**Description**
Spatial selection of a 3D file indicates missing element although its centroid lies within the given Polygon. Converting the selection to 2D via layer specification yields "correct" output. 

**To Reproduce**
In [24) onwards >> https://github.com/DHI/mikeio/blob/dfsu_area_selection/notebooks/spatial_Selection_Element_IDs.ipynb

![image](https://user-images.githubusercontent.com/98176193/175567993-2666614d-0d73-4157-97b1-c1b44ce6e3c4.png)

**Expected behavior**
Indication of 10 elements, consistent to 2D.

System information:
Python 3.9.12
MIKE IO 1.0.1

**Comment by jsmariegaard** [comment]
Thanks for reporting, @ovho-dhi , this may have been fixed in #373 and merged to main a few days ago (or even in #371 + #372 which have been released as mikeio==1.0.2). Could you please check with the latest dev version? [let me know if you need instructions on how to get this]

**Comment by jsmariegaard** [comment]
@ovho-dhi - could you please try if the problem still persists with mikeio==1.0.3 released yesterday? Thanks

**Comment by ovho-dhi** [comment]
@jsmariegaard - i just rerun the notebook with mikeio==1.0.3 and still receive the exact same inconsistent output.

**Comment by jsmariegaard** [comment]
Thanks @ovho-dhi - I will take a look again.
